default: &DEFAULT

  #General
  verbose: True
  device: 'cuda:0'
  interactive: True
  lattice_dataset: 'strut'
  lattice_data_file_path: './data/struct/dataset_strut.pkl'
  vae_file_path: './data/struct/vae.pickle'
  cell_width: 40
  nelx: 40
  nely: 40
  len_x: 1
  len_y: 1
  max_grad: 10 # 10
  example: 3  # see ExperiemntSetting Class
  cell_type: 'lattice' # lattice or solid
  simplexDim: 8
  fno: True
  nn_type: 'FNO' # cnn no
  record_real_compliance: False
  saveFrame: False
  numModex: 8
  numModey: 4
  searchMode: 'simplex' # simplex or cubic 
  latentDim: 16
  numLayers: 5 # the depth of the NN
  numNeuronsPerLyr: 20 # the height of the NN
  minEpochs: 100  # minimum number of iterations
  maxEpochs: 5000  # Max number of iterations
  penal: 2  # SIMP penalization constant, starting value
  Emin: 1e-6
  Emax: 1.0
  nu: 0.3
  useSavedNet: False # use a net previouslySaved  as starting point (exampleName_nelx_nely.nt in ./results folder)
  desiredVolumeFraction: 0.4
  learningRate: 0.01 
  data_dir: './data/struct'
  results_dir: './results'

  wandb:
      log: False
      name: None # If None, config will be used but you can override it here
      group: ""
      project: ""
      entity: "" # put your username here
      sweep: False
      log_output: True
      eval_interval: 1